In [ ]:
#Question 1
arr = np.array([1, 2, 3, 4, 5])

print("Original Array:", arr)
print("Add 2:", arr + 2)
print("Multiply by 3:", arr * 3)
print("Divide by 2:", arr / 2)

Original Array: [1 2 3 4 5]
Add 2: [3 4 5 6 7]
Multiply by 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]


In [ ]:
#Question 2
import numpy as np
arr=np.array([1,2,3,6,4,5])
print("Original array:",arr)
print("Reversed array:",arr[::-1])
#2b
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values,counts=np.unique(y,return_counts=True)
max_value=values[np.argmax(counts)]
indices=np.where(y==max_value)[0]
print("Array:", y)
print("Most Frequent Value:", max_value)
print("Indices:", indices)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]
Array: [1 1 1 2 3 4 2 4 3 3]
Most Frequent Value: 1
Indices: [0 1 2]


In [ ]:
#Question3
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print("First row and 2nd column",arr[0,1])
print("3rd row and first column",arr[2,0])

First row and 2nd column 20
3rd row and first column 70


In [ ]:
#Question 4
Your_Name = np.linspace(10, 100, 25)

print("Array:\n", Your_Name)
print("Dimensions:", Your_Name.ndim)
print("Shape:", Your_Name.shape)
print("Total Elements:", Your_Name.size)
print("Data Type:", Your_Name.dtype)
print("Bytes Consumed:", Your_Name.nbytes)
transpose_arr = Your_Name.reshape(25,1)
print("\nTranspose using reshape():")
print(transpose_arr)
print("\nUsing T attribute:")
print(Your_Name.T)
print("\nNote: T has no effect on a 1-D array.")



Q4
Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Bytes Consumed: 200

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Note: T has no effect on a 1-D array.


In [ ]:
#Question 5
ucs420_your_name = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print("Original Array:\n", ucs420_your_name)

print("Mean:", np.mean(ucs420_your_name))
print("Median:", np.median(ucs420_your_name))
print("Maximum:", np.max(ucs420_your_name))
print("Minimum:", np.min(ucs420_your_name))
print("Unique Elements:", np.unique(ucs420_your_name))

# Reshape
reshaped_ucs420_your_name = ucs420_your_name.reshape(4,3)

print("\nReshaped Array (4x3):")
print(reshaped_ucs420_your_name)

# Resize
resized_ucs420_your_name = np.resize(ucs420_your_name, (2,3))

print("\nResized Array (2x3):")
print(resized_ucs420_your_name)


Q5
Original Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
[[10 20 30]
 [40 50 60]]
