In [ ]:
##Question 1
import numpy as np
#(a)
temperature=np.array([25,28,31,35,38,27,33,40])
corrected_temp=temperature+2
print("The Original temperature",temperature)
print("The Corrected temperature",corrected_temp)
#(b)
fahrenheit=(9/5)*corrected_temp+32
print("The converted temperature in fahrenheit",fahrenheit)
#(c)
greater_than_32=corrected_temp[corrected_temp>32]
print("Reading greater than 32°C",greater_than_32)
#(d)
count=np.sum(corrected_temp>32)
print("Number of reading :",count)


The Original temperature [25 28 31 35 38 27 33 40]
The Corrected temperature [27 30 33 37 40 29 35 42]
The converted temperature in fahrenheit [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Reading greater than 32°C [33 37 40 35 42]
Number of reading : 5


In [5]:
##Question 2
import numpy as np
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
#(a)
total_steps=np.sum(steps)
print("Total Steps:",total_steps)
#(b)
mean_steps=np.mean(steps)
print("Mean Steps:",mean_steps)
#(c)
maximum=np.max(steps)
minimum=np.min(steps)
print("The Maximum steps:",maximum)
print("The Minimum steps:",minimum)
#(d)
day_total=np.sum(steps,axis=0)
print("Total steps in for each day",day_total)
#(e)
user_total=np.sum(steps,axis=1)
print("Total steps in for each user",user_total)


Total Steps: 84200
Mean Steps: 7016.666666666667
The Maximum steps: 9500
The Minimum steps: 4500
Total steps in for each day [26500 27300 30400]
Total steps in for each user [18300 24500 14400 27000]


In [6]:
import numpy as np

# a. Create original array
original = np.array([1, 2, 3, 4, 5, 6])

print("Original array:", original)


# b. Slice from index 1 to 4
subset = original[1:5]

print("Subset:", subset)


# c. Modify first element of subset
subset[0] = 999

print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)


# d. Create another slice using copy()
copied = original[1:5].copy()

copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)


# e. Create numbers 1 to 12 and reshape into 3 x 4
matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)


# f. Indexing and slicing

# First row
first_row = matrix[0]

# Last row
last_row = matrix[-1]

# Second column
second_column = matrix[:, 1]

# Rows 1-2 and columns 2-3
selected_elements = matrix[1:3, 2:4]

print("\nFirst row:", first_row)
print("Last row:", last_row)
print("Second column:", second_column)
print("Rows 1-2 and columns 2-3:")
print(selected_elements)


# g. Flatten and ravel
flattened = matrix.flatten()
raveled = matrix.ravel()

print("\nFlatten:", flattened)
print("Ravel:", raveled)


# h. Modify ravel array
raveled[0] = 1000

print("\nAfter modifying ravel:")
print("Ravel:", raveled)
print("Original matrix:")
print(matrix)


# i. Modify flatten array
flattened[1] = 2000

print("\nAfter modifying flatten:")
print("Flatten:", flattened)
print("Original matrix:")
print(matrix)


# j. Display shape, ndim, size and dtype
print("\nMatrix properties:")
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original array: [1 2 3 4 5 6]
Subset: [2 3 4 5]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten:
Flatten: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

Matrix properties:
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [9]:
import numpy as np
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y=np.array([40, 65, 30, 85])
print("Shape of X",X.shape)
print("Dimension of X",X.ndim)
#(b)
X_t=X.T
print("\nTranspose of X:",X_t)
#(c)
XT_X = X.T @ X

print("\nX.T @ X:")
print(XT_X)
#(d)
inverse = np.linalg.inv(XT_X)

print("\nInverse of X.T @ X:")
print(inverse)
#(e)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("\nOLS coefficients:")
print(beta)

#(f)
print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])
#(g)
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nPredicted assistance score:", predicted_score)

Shape of X (4, 3)
Dimension of X 2

Transpose of X: [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.15921454159484516
Activity coefficient: 0.14083852991905366
Stress coefficient: 10.063022422714608

Predicted assistance score: 75.27862544779018
